image:
  file: gitpod/gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview

tasks:
  - init: yarn
    command: yarn build
    command: printf '%s\n' "The build has finished, you can now run 'yarn start' to expose the environment on port 3000"